# Generated by Django 5.0.10 on 2026-03-10 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("PS", "Petite Section"),
                            ("MS", "Moyenne Section"),
                            ("GS", "Grande Section"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("LANGAGE", "Langage"),
                            ("MOTRICITE", "Motricité"),
                            ("MATHS", "Maths"),
                            ("ART", "Arts"),
                            ("EXPLORER", "Explorer le monde"),
                            ("VIVRE", "Vivre ensemble"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_minutes", models.IntegerField()),
                ("materials", models.TextField(blank=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
